sdf

diff --git a/.github/workflows/snowflake-deploy.yml b/.github/workflows/snowflake-deploy.yml
--- a/.github/workflows/snowflake-deploy.yml
+++ b/.github/workflows/snowflake-deploy.yml
@@ -82,7 +82,7 @@ jobs:
               
               # Execute the SQL file. If the command fails, the `else` block will run.
               # This prevents the entire workflow from stopping on a single error.
-              snow sql -q "USE DATABASE ${SNOWFLAKE_DATABASE};" 
+              snow sql -q "USE DATABASE ${SNOWFLAKE_DATABASE};" --temporary-connection || true
 
               if snow sql -f "$file"  > output.log 2>&1; then
                 # This block runs on SUCCESS.
@@ -189,7 +189,7 @@ jobs:
           while IFS= read -r file; do
             if [ -n "$file" ]; then
               echo "Executing $file..."
-              snow sql -q "USE DATABASE ${SNOWFLAKE_DATABASE};" 
+              snow sql -q "USE DATABASE ${SNOWFLAKE_DATABASE};" --temporary-connection || true
               
               # Execute the SQL file. If the command fails, the `else` block will run.
               # This prevents the entire workflow from stopping on a single error.
@@ -208,7 +208,7 @@ jobs:
                 OVERALL_STATUS=1
               fi 
               # Construct and run a SQL query to log the outcome (SUCCESS or FAILED) to the history table.
-              LOG_QUERY="INSERT INTO CICD_DEMO_DB.TECH.DEPLOYMENT_HISTORY (FILENAME, COMMIT_SHA, GITHUB_ACTOR, STATUS, ERROR_MESSAGE) VALUES ('$FILE', '${{ github.sha }}', '${{ github.actor }}', '$STATUS', '$ERROR_MSG');"
+              LOG_QUERY="INSERT INTO QUICKSTART_COMMON.PUBLIC.DEPLOYMENT_HISTORY (FILENAME, COMMIT_SHA, GITHUB_ACTOR, STATUS, ERROR_MESSAGE) VALUES ('$FILE', '${{ github.sha }}', '${{ github.actor }}', '$STATUS', '$ERROR_MSG');"
               snow sql -q "$LOG_QUERY" 
               echo "Logged deployment for $FILE with status: $STATUS"              
             fi
